// GENERATED by sync.py — do not hand-edit.
export type TimelineEntry = {scene: string; from: number; duration: number; props?: Record<string, unknown>};
export const timeline: TimelineEntry[] = [
  {scene: "01-cold-open", from: 0, duration: 63},
  {scene: "02-bear-meme", from: 63, duration: 138},
  {scene: "03-silly-secrets", from: 201, duration: 120},
  {scene: "04-night-post", from: 321, duration: 111},
  {scene: "05-the-words", from: 432, duration: 96},
  {scene: "06-ink-bleed", from: 528, duration: 39},
  {scene: "07-case-closed", from: 567, duration: 78},
  {scene: "09-one-reply", from: 645, duration: 195},
];
export const voFile: string | null = "vo/story-008-vo-en.mp3";
