// GENERATED by sync.py — do not hand-edit.
export type TimelineEntry = {scene: string; from: number; duration: number; props?: Record<string, unknown>};
export const timeline: TimelineEntry[] = [
  {scene: "01-cold-open", from: 0, duration: 147},
  {scene: "02-bear-meme", from: 147, duration: 174},
  {scene: "03-silly-secrets", from: 321, duration: 183},
  {scene: "05-the-words", from: 504, duration: 273},
  {scene: "04-night-post", from: 777, duration: 312},
  {scene: "05-the-words", from: 1089, duration: 69},
  {scene: "06-ink-bleed", from: 1158, duration: 150},
  {scene: "07-case-closed", from: 1308, duration: 123},
  {scene: "02-bear-clip", from: 1431, duration: 21},
  {scene: "03-post-clip", from: 1452, duration: 18},
  {scene: "05-explosion-clip", from: 1470, duration: 18},
  {scene: "08-explosion", from: 1488, duration: 120},
  {scene: "09-one-reply", from: 1608, duration: 150},
];
export const voFile: string | null = "vo/story-003-vo-v3.mp3";
