// GENERATED by sync.py — do not hand-edit.
export type TimelineEntry = {scene: string; from: number; duration: number; props?: Record<string, unknown>};
export const timeline: TimelineEntry[] = [
  {scene: "01-cold-open", from: 0, duration: 33},
  {scene: "02-bear-meme", from: 33, duration: 33},
  {scene: "03-silly-secrets", from: 66, duration: 96},
  {scene: "04-night-post", from: 162, duration: 123},
  {scene: "05-the-words", from: 285, duration: 135},
  {scene: "06-ink-bleed", from: 420, duration: 117},
  {scene: "07-case-closed", from: 537, duration: 36},
  {scene: "08-explosion", from: 573, duration: 60},
  {scene: "09-one-reply", from: 633, duration: 219},
];
export const voFile: string | null = "vo/story-007-vo-en.mp3";
