// GENERATED by sync.py — do not hand-edit.
export type TimelineEntry = {scene: string; from: number; duration: number; props?: Record<string, unknown>};
export const timeline: TimelineEntry[] = [
  {scene: "01-cold-open", from: 0, duration: 243},
  {scene: "02-bear-meme", from: 243, duration: 258},
  {scene: "03-silly-secrets", from: 501, duration: 270},
  {scene: "04-night-post", from: 771, duration: 156},
  {scene: "05-the-words", from: 927, duration: 153},
  {scene: "06-ink-bleed", from: 1080, duration: 141},
  {scene: "07-case-closed", from: 1221, duration: 141},
  {scene: "04-night-post", from: 1362, duration: 21},
  {scene: "05-the-words", from: 1383, duration: 21},
  {scene: "06-ink-bleed", from: 1404, duration: 24},
  {scene: "08-explosion", from: 1428, duration: 120},
  {scene: "09-one-reply", from: 1548, duration: 120},
];
export const voFile: string | null = "vo/story-003-vo.mp3";
