// GENERATED by sync.py — do not hand-edit.
export type TimelineEntry = {scene: string; from: number; duration: number; props?: Record<string, unknown>};
export const timeline: TimelineEntry[] = [
  {scene: "01-cold-open", from: 0, duration: 102},
  {scene: "02-bear-meme", from: 102, duration: 135},
  {scene: "03-silly-secrets", from: 237, duration: 162},
  {scene: "04-night-post", from: 399, duration: 105},
  {scene: "05-the-words", from: 504, duration: 78},
  {scene: "06-ink-bleed", from: 582, duration: 78},
  {scene: "07-case-closed", from: 660, duration: 81},
  {scene: "08-explosion", from: 741, duration: 63},
  {scene: "09-one-reply", from: 804, duration: 198},
];
export const voFile: string | null = "vo/story-006-vo-hi.mp3";
