// GENERATED by sync.py — do not hand-edit.
export type TimelineEntry = {scene: string; from: number; duration: number; props?: Record<string, unknown>};
export const timeline: TimelineEntry[] = [
  {scene: "wg1-invitation", from: 0, duration: 108},
  {scene: "wg2-page-turn", from: 108, duration: 87},
  {scene: "wg3-bedroom", from: 195, duration: 216},
  {scene: "wg4-the-smile", from: 411, duration: 126},
  {scene: "wg5-envelope", from: 537, duration: 78},
  {scene: "wg6-party-recording", from: 615, duration: 210},
  {scene: "wg7-they-chose-her", from: 825, duration: 114},
  {scene: "wg8-lost-everything", from: 939, duration: 108},
  {scene: "wg9-planning", from: 1047, duration: 132},
];
export const voFile: string | null = "vo/story-002-p1-vo.mp3";
